# Generated by Django 5.0.1 on 2024-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='date',
            field=models.DateField(default='2024-02-19'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
