# Generated by Django 5.0.1 on 2024-02-20 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogs_date_alter_blogs_dislikes_alter_blogs_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
