# Generated by Django 5.0.1 on 2024-02-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profilePic',
            field=models.ImageField(default='default.jpg', max_length=5000, upload_to='ProfilePic'),
        ),
    ]
