# Generated by Django 5.0.1 on 2024-02-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userinfo_name_alter_userinfo_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='gender',
        ),
    ]
