# Generated by Django 5.0.1 on 2024-02-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_userinfo_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='likes',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
