# Generated by Django 5.0.1 on 2024-02-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_name_userinfo_name_post_delete_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='General', max_length=250),
        ),
    ]
