# Generated by Django 5.0.1 on 2024-02-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
